//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VC.WebApi.Infrastructure.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorTitle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorTitle() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VC.WebApi.Infrastructure.Errors.ErrorTitle", typeof(ErrorTitle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        public static string bad_request {
            get {
                return ResourceManager.GetString("bad-request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During the processing a conflict occured..
        /// </summary>
        public static string conflict {
            get {
                return ResourceManager.GetString("conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access to this resoruce is forbidden..
        /// </summary>
        public static string forbidden {
            get {
                return ResourceManager.GetString("forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway timeout.
        /// </summary>
        public static string gateway_timeout {
            get {
                return ResourceManager.GetString("gateway-timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal operation created an unexpected error..
        /// </summary>
        public static string internal_server_error {
            get {
                return ResourceManager.GetString("internal-server-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Short Name.
        /// </summary>
        public static string LevelShortName {
            get {
                return ResourceManager.GetString("LevelShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method not allowd.
        /// </summary>
        public static string method_not_allowd {
            get {
                return ResourceManager.GetString("method-not-allowd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access needs authentication..
        /// </summary>
        public static string not_authenticated {
            get {
                return ResourceManager.GetString("not-authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource was not found..
        /// </summary>
        public static string not_found {
            get {
                return ResourceManager.GetString("not-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precondition required..
        /// </summary>
        public static string precondiction_required {
            get {
                return ResourceManager.GetString("precondiction-required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precondition failed.
        /// </summary>
        public static string precondition_failed {
            get {
                return ResourceManager.GetString("precondition-failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Unavailable.
        /// </summary>
        public static string service_unavailable {
            get {
                return ResourceManager.GetString("service-unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more validation errors occured..
        /// </summary>
        public static string validation_error {
            get {
                return ResourceManager.GetString("validation-error", resourceCulture);
            }
        }
    }
}
