//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VC.WebApi.Infrastructure.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorDetail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VC.WebApi.Infrastructure.Errors.ErrorDetail", typeof(ErrorDetail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;One of two values is required&quot;:&quot;{0} or {1} is required.&quot;.
        /// </summary>
        public static string A_Or_B_Required {
            get {
                return ResourceManager.GetString("A_Or_B_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of affected rows for {0} with id [{1}] should be {2}, but was {3}..
        /// </summary>
        public static string Affected_Rows {
            get {
                return ResourceManager.GetString("Affected_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests with &apos;allLanguages&apos; query parameter must not have &apos;language&apos; query paramaters..
        /// </summary>
        public static string AllLangauages_Request_Must_Not_Have_Language_Params {
            get {
                return ResourceManager.GetString("AllLangauages_Request_Must_Not_Have_Language_Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must include at least one lowercase character..
        /// </summary>
        public static string At_Least_One_Lowercase_Character {
            get {
                return ResourceManager.GetString("At_Least_One_Lowercase_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must include at least one number..
        /// </summary>
        public static string At_Least_One_Number {
            get {
                return ResourceManager.GetString("At_Least_One_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must include at least one special character..
        /// </summary>
        public static string At_Least_One_Special_Character {
            get {
                return ResourceManager.GetString("At_Least_One_Special_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must include at least one uppercase character..
        /// </summary>
        public static string At_Least_One_Uppercase_Character {
            get {
                return ResourceManager.GetString("At_Least_One_Uppercase_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must have exactly {1} characters..
        /// </summary>
        public static string Char_Length_Incorrect {
            get {
                return ResourceManager.GetString("Char_Length_Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains invalid characters.
        /// </summary>
        public static string Contains_Invalid_Characters {
            get {
                return ResourceManager.GetString("Contains_Invalid_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid value for a system language (CultureInfo)..
        /// </summary>
        public static string Culture_Name {
            get {
                return ResourceManager.GetString("Culture_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database is not available..
        /// </summary>
        public static string Database_Not_Available {
            get {
                return ResourceManager.GetString("Database_Not_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date can&apos;t be before {0}..
        /// </summary>
        public static string Date_Cant_Be_Before_Min_Date {
            get {
                return ResourceManager.GetString("Date_Cant_Be_Before_Min_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can&apos;t be in the future..
        /// </summary>
        public static string Date_Cant_Be_In_Future {
            get {
                return ResourceManager.GetString("Date_Cant_Be_In_Future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign key constraint violation. Referenced table: {0} Constraint name: {1} Command: {2}.
        /// </summary>
        public static string Delete_Foreign_Key_Violation {
            get {
                return ResourceManager.GetString("Delete_Foreign_Key_Violation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has duplicates for values &apos;{1}&apos;..
        /// </summary>
        public static string Duplicate_Values {
            get {
                return ResourceManager.GetString("Duplicate_Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; exists already..
        /// </summary>
        public static string Exists_Already {
            get {
                return ResourceManager.GetString("Exists_Already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with id [{1}] exists already..
        /// </summary>
        public static string Exists_With_Id {
            get {
                return ResourceManager.GetString("Exists_With_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation failed unexpectedly..
        /// </summary>
        public static string Failed_Unexpectedly {
            get {
                return ResourceManager.GetString("Failed_Unexpectedly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload failed &apos;{0}&apos;.
        /// </summary>
        public static string File_Upload_Failed {
            get {
                return ResourceManager.GetString("File_Upload_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The from date &apos;{0}&apos; must be before the until date &apos;{1}&apos;..
        /// </summary>
        public static string FromDate_Must_Be_Before_UntilDate {
            get {
                return ResourceManager.GetString("FromDate_Must_Be_Before_UntilDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The from date or the until date must have a valid value..
        /// </summary>
        public static string FromDate_Or_UntilDate_Must_Be_Not_Null {
            get {
                return ResourceManager.GetString("FromDate_Or_UntilDate_Must_Be_Not_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hour exists twice, because the clock was turned back. You need to specifiy if the hour belongs to the first (A) or the second (B) period..
        /// </summary>
        public static string Hour_Ambigiush {
            get {
                return ResourceManager.GetString("Hour_Ambigiush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hour does not exists, because the clock was turned forward, e.g. by a change to daylight savings time or a general time change for that zone..
        /// </summary>
        public static string Hour_Skipped {
            get {
                return ResourceManager.GetString("Hour_Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find {0} with id &apos;{1}&apos;..
        /// </summary>
        public static string Id_Not_Found {
            get {
                return ResourceManager.GetString("Id_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid value for &apos;{0}&apos;..
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not recognized as a date..
        /// </summary>
        public static string Invalid_Date {
            get {
                return ResourceManager.GetString("Invalid_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid visibility for an event..
        /// </summary>
        public static string Invalid_Event_Visibility {
            get {
                return ResourceManager.GetString("Invalid_Event_Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid Guid..
        /// </summary>
        public static string Invalid_Guid {
            get {
                return ResourceManager.GetString("Invalid_Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Language &apos;{0}&apos; is not valid..
        /// </summary>
        public static string Invalid_Language {
            get {
                return ResourceManager.GetString("Invalid_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid Regex expression. Details: {1}.
        /// </summary>
        public static string Invalid_Regex {
            get {
                return ResourceManager.GetString("Invalid_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input string &apos;{0}&apos; is not in the correct RGBA format..
        /// </summary>
        public static string Invalid_RGBA_Format {
            get {
                return ResourceManager.GetString("Invalid_RGBA_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid system language..
        /// </summary>
        public static string Invalid_System_Language {
            get {
                return ResourceManager.GetString("Invalid_System_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid URI..
        /// </summary>
        public static string Invalid_Uri {
            get {
                return ResourceManager.GetString("Invalid_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid value for &apos;{0}&apos;.
        /// </summary>
        public static string Invalid_Value {
            get {
                return ResourceManager.GetString("Invalid_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} and {2} characters..
        /// </summary>
        public static string Length_Out_Of_Range {
            get {
                return ResourceManager.GetString("Length_Out_Of_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is too long. The maximum length is {1} characters..
        /// </summary>
        public static string Max_Char_Length_Exceeded {
            get {
                return ResourceManager.GetString("Max_Char_Length_Exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value exceeds the precision. The maximum number of decimal places is {0}..
        /// </summary>
        public static string Max_Decimal_Places_Exceeded {
            get {
                return ResourceManager.GetString("Max_Decimal_Places_Exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is too long. The maximum length is {1} digits..
        /// </summary>
        public static string Max_Digit_Length_Exceeded {
            get {
                return ResourceManager.GetString("Max_Digit_Length_Exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of {0} exeeds the maximum of {1}..
        /// </summary>
        public static string Max_Value_Exceeded {
            get {
                return ResourceManager.GetString("Max_Value_Exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is too short. The minimum length is {1} characters..
        /// </summary>
        public static string Min_Char_Length_Deceeded {
            get {
                return ResourceManager.GetString("Min_Char_Length_Deceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is too short. The minimum length is {1} digits..
        /// </summary>
        public static string Min_Digit_Length_Deceeded {
            get {
                return ResourceManager.GetString("Min_Digit_Length_Deceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is smaller than the minimum of {0}..
        /// </summary>
        public static string Min_Value_Deceeded {
            get {
                return ResourceManager.GetString("Min_Value_Deceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Value for Valid MultiLanguage Value.
        /// </summary>
        public static string Missing_Value_for_Valid_MultiLanguage_Json {
            get {
                return ResourceManager.GetString("Missing_Value_for_Valid_MultiLanguage_Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value could not be removed. It does not exist in language &apos;{0}&apos;..
        /// </summary>
        public static string ML_Cant_Remove_Language_Does_Not_Exists {
            get {
                return ResourceManager.GetString("ML_Cant_Remove_Language_Does_Not_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value can&apos;t be removed in language {0}. A value is required in at least one language..
        /// </summary>
        public static string ML_Cant_Remove_Language_Requires_At_Least_One_Language {
            get {
                return ResourceManager.GetString("ML_Cant_Remove_Language_Requires_At_Least_One_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value does not exist in language &apos;{0}&apos;..
        /// </summary>
        public static string ML_Language_Does_Not_Exists {
            get {
                return ResourceManager.GetString("ML_Language_Does_Not_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires a value in at least one language..
        /// </summary>
        public static string ML_Requires_At_Least_One_Language {
            get {
                return ResourceManager.GetString("ML_Requires_At_Least_One_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been modified by another user..
        /// </summary>
        public static string Modified_By_Other_User {
            get {
                return ResourceManager.GetString("Modified_By_Other_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be empty..
        /// </summary>
        public static string Must_Be_Empty {
            get {
                return ResourceManager.GetString("Must_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be a positive integer..
        /// </summary>
        public static string Must_Be_Pos_Int {
            get {
                return ResourceManager.GetString("Must_Be_Pos_Int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be a positive integer or null..
        /// </summary>
        public static string Must_Be_Pos_Int_Or_Zero {
            get {
                return ResourceManager.GetString("Must_Be_Pos_Int_Or_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be zero..
        /// </summary>
        public static string Must_Be_Zero {
            get {
                return ResourceManager.GetString("Must_Be_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must not be empty..
        /// </summary>
        public static string Must_Not_Be_Empty {
            get {
                return ResourceManager.GetString("Must_Not_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can&apos;t be zero..
        /// </summary>
        public static string Must_Not_Be_Zero {
            get {
                return ResourceManager.GetString("Must_Not_Be_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource &apos;{0}&apos; can&apos;t be deleted, because it is referenced by the resource &apos;{1}&apos;..
        /// </summary>
        public static string No_Deletion_For_Linked_Resource {
            get {
                return ResourceManager.GetString("No_Deletion_For_Linked_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file was uploaded..
        /// </summary>
        public static string No_File_Uploaded {
            get {
                return ResourceManager.GetString("No_File_Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can&apos;t have any leading or trailing space characters..
        /// </summary>
        public static string No_Leading_Or_Trailing_Space {
            get {
                return ResourceManager.GetString("No_Leading_Or_Trailing_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission for this command..
        /// </summary>
        public static string No_Permission_For_Command {
            get {
                return ResourceManager.GetString("No_Permission_For_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to access the field(s) &apos;{0}&apos;..
        /// </summary>
        public static string No_Permission_For_Field {
            get {
                return ResourceManager.GetString("No_Permission_For_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to access the object &apos;{0}&apos;..
        /// </summary>
        public static string No_Permission_For_Object {
            get {
                return ResourceManager.GetString("No_Permission_For_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to access the fields of object &apos;{0}&apos;..
        /// </summary>
        public static string No_Permission_For_Object_Fields {
            get {
                return ResourceManager.GetString("No_Permission_For_Object_Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission for this request..
        /// </summary>
        public static string No_Permission_For_Request {
            get {
                return ResourceManager.GetString("No_Permission_For_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of &apos;{0}&apos; is not a valid JSON format for multi-language text. Example: {{&quot;de&quot;:&quot;German&quot;,&quot;en&quot;:&quot;English&quot;}}..
        /// </summary>
        public static string Not_a_Valid_MultiLanguage_Json_Format {
            get {
                return ResourceManager.GetString("Not_a_Valid_MultiLanguage_Json_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only image files of type jpg, png, gif, webp, and svg and are allowed..
        /// </summary>
        public static string Not_An_Accepted_Image_Type {
            get {
                return ResourceManager.GetString("Not_An_Accepted_Image_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Authenticated.
        /// </summary>
        public static string Not_Authenticated {
            get {
                return ResourceManager.GetString("Not_Authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find {0}..
        /// </summary>
        public static string Not_Found {
            get {
                return ResourceManager.GetString("Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource &apos;{0}&apos; with Id &apos;{1}&apos; was not found..
        /// </summary>
        public static string Not_Found_Resource_With_Id {
            get {
                return ResourceManager.GetString("Not_Found_Resource_With_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can&apos;t contain only whitespace..
        /// </summary>
        public static string Not_Only_Whitespace {
            get {
                return ResourceManager.GetString("Not_Only_Whitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2} for {0} with id [{1}] was not successful..
        /// </summary>
        public static string Not_Successful {
            get {
                return ResourceManager.GetString("Not_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} may consists of digits only..
        /// </summary>
        public static string Only_Digits {
            get {
                return ResourceManager.GetString("Only_Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the requested page..
        /// </summary>
        public static string Page_Not_Found {
            get {
                return ResourceManager.GetString("Page_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The country code may only consist of a maximum of {0} digits and an optional leading &apos;+&apos; sign..
        /// </summary>
        public static string Phone_Country_Code_Invalid {
            get {
                return ResourceManager.GetString("Phone_Country_Code_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of a phone number without extension is {0} digits plus an optional leading &apos;+&apos; sign..
        /// </summary>
        public static string Phone_Public_Part_Max_Length_Exceeded {
            get {
                return ResourceManager.GetString("Phone_Public_Part_Max_Length_Exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A price can&apos;t have an negative amount..
        /// </summary>
        public static string Price_Cant_Be_Negative {
            get {
                return ResourceManager.GetString("Price_Cant_Be_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request body requires at least one field..
        /// </summary>
        public static string Request_Body_Requires_At_Least_One_Field {
            get {
                return ResourceManager.GetString("Request_Body_Requires_At_Least_One_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Field &apos;{0}&apos; is required..
        /// </summary>
        public static string Required_Field {
            get {
                return ResourceManager.GetString("Required_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is required..
        /// </summary>
        public static string Required_File {
            get {
                return ResourceManager.GetString("Required_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; is required..
        /// </summary>
        public static string Required_Parameter {
            get {
                return ResourceManager.GetString("Required_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource &apos;{0}&apos; at URI &apos;{1}&apos; can&apos;t be read..
        /// </summary>
        public static string Resource_At_Uri_Cant_Be_Read {
            get {
                return ResourceManager.GetString("Resource_At_Uri_Cant_Be_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource &apos;{0}&apos; with ID &apos;{1}&apos; does not exist..
        /// </summary>
        public static string Resource_Does_Not_Exist {
            get {
                return ResourceManager.GetString("Resource_Does_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource &apos;{0}&apos; can&apos;t be found at URI &apos;{1}&apos;..
        /// </summary>
        public static string Resource_Not_Found_At_Uri {
            get {
                return ResourceManager.GetString("Resource_Not_Found_At_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of HTTP-Route id does not match value of DTO.Id..
        /// </summary>
        public static string Route_ID_Not_Match_DTO_ID {
            get {
                return ResourceManager.GetString("Route_ID_Not_Match_DTO_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified hour discriminator ({0}) is not valid for local time..
        /// </summary>
        public static string TimeDiscriminator_Not_Valid {
            get {
                return ResourceManager.GetString("TimeDiscriminator_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; contains already a value &apos;{1}&apos; in the language &apos;{2}&apos;..
        /// </summary>
        public static string Unique_MLValue_Required {
            get {
                return ResourceManager.GetString("Unique_MLValue_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; contains already a value &apos;{1}&apos;..
        /// </summary>
        public static string Unique_Value_Required {
            get {
                return ResourceManager.GetString("Unique_Value_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaginated request with paged = false must not have a &apos;pageNumber&apos; or &apos;pageSize&apos; query paramater..
        /// </summary>
        public static string Unpaged_Request_Must_Not_Have_PageNumber_Or_PageSize_Params {
            get {
                return ResourceManager.GetString("Unpaged_Request_Must_Not_Have_PageNumber_Or_PageSize_Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update data is mising..
        /// </summary>
        public static string Update_Data_Missing {
            get {
                return ResourceManager.GetString("Update_Data_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded file is empty..
        /// </summary>
        public static string Uploaded_File_Is_Empty {
            get {
                return ResourceManager.GetString("Uploaded_File_Is_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded_File_MaxSize_Exceeded.
        /// </summary>
        public static string Uploaded_File_MaxSize_Exceeded {
            get {
                return ResourceManager.GetString("Uploaded_File_MaxSize_Exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded file is empty..
        /// </summary>
        public static string Uploaded_File_X_Is_Empty {
            get {
                return ResourceManager.GetString("Uploaded_File_X_Is_Empty", resourceCulture);
            }
        }
    }
}
